AWSTemplateFormatVersion: '2010-09-09'
Description: 'Jenkins CI/CD Pipeline for Microservice Deployment'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: ['dev', 'staging', 'prod']
    Description: Deployment environment
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: MicroserviceEnv

Resources:
  # Jenkins IAM Role
  JenkinsMasterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess

  # CodeBuild Project for Backend
  BackendBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${EnvironmentName}-backend-build
      ServiceRole: !GetAtt JenkinsMasterRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: https://github.com/yourusername/microservice-repo.git
        BuildSpec: buildspec-backend.yml

  # CodeBuild Project for Frontend
  FrontendBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${EnvironmentName}-frontend-build
      ServiceRole: !GetAtt JenkinsMasterRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: GITHUB
        Location: https://github.com/yourusername/frontend-repo.git
        BuildSpec: buildspec-frontend.yml

Outputs:
  BackendBuildProjectName:
    Description: Backend Build Project Name
    Value: !Ref BackendBuildProject

  FrontendBuildProjectName:
    Description: Frontend Build Project Name
    Value: !Ref FrontendBuildProject