AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 DNS Configuration for Microservices'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: ['dev', 'staging', 'prod']
    Description: Deployment environment

  RootDomainName:
    Type: String
    Default: yourdomain.com
    Description: Root domain name for the microservices

  HostedZoneId:
    Type: String
    Default: ''
    Description: Optional existing Hosted Zone ID. If not provided, a new zone will be created.

  CloudFrontDomainName:
    Type: String
    Description: CloudFront distribution domain name
    Default: d1darej3ompb63.cloudfront.net

  ApiEndpointDomain:
    Type: String
    Description: API Gateway or Backend Service Domain
    Default: yourdomain.com

Conditions:
  CreateNewHostedZone: !Equals [!Ref HostedZoneId, '']

Resources:
  MicroserviceHostedZone:
    Type: AWS::Route53::HostedZone
    Condition: CreateNewHostedZone
    Properties:
      Name: !Ref RootDomainName

  MicroserviceHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: /health
        FullyQualifiedDomainName: !Ref ApiEndpointDomain
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3

  FrontendHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        ResourcePath: /
        FullyQualifiedDomainName: !Ref CloudFrontDomainName
        Port: 443
        RequestInterval: 30
        FailureThreshold: 3

  MicroserviceDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        !If 
          - CreateNewHostedZone
          - !Ref MicroserviceHostedZone
          - !Ref HostedZoneId
      Name: !Sub api.${RootDomainName}.
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront's global hosted zone ID
        DNSName: !Ref CloudFrontDomainName

  FrontendDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: 
        !If 
          - CreateNewHostedZone
          - !Ref MicroserviceHostedZone
          - !Ref HostedZoneId
      Name: !Sub app.${RootDomainName}.
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront's global hosted zone ID
        DNSName: !Ref CloudFrontDomainName

Outputs:
  MicroserviceHostedZoneId:
    Description: Hosted Zone ID for Microservice Domain
    Value: 
      !If 
        - CreateNewHostedZone
        - !Ref MicroserviceHostedZone
        - !Ref HostedZoneId
    Export:
      Name: !Sub ${Environment}-MicroserviceHostedZoneId

  MicroserviceHealthCheckId:
    Description: Health Check ID for Microservice Endpoint
    Value: !Ref MicroserviceHealthCheck
    Export:
      Name: !Sub ${Environment}-MicroserviceHealthCheckId

  FrontendHealthCheckId:
    Description: Health Check ID for Frontend Endpoint
    Value: !Ref FrontendHealthCheck
    Export:
      Name: !Sub ${Environment}-FrontendHealthCheckId